services:
  mariadb:
    image: mariadb:10.6
    platform: linux/amd64
    container_name: mariadb
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: docker.io/redis:alpine
    platform: linux/amd64
    ports:
      - "6379:6379"

volumes:
  db-data: